### ISSUE TITLE
ModuleNotFoundError: No module named 'ru_address.source'

### ISSUE THREAD

**Issue by unwo** [shadz3rg/ru_address#1]
Ошибка при запуске:
$ ru_address
Traceback (most recent call last):
  File "/usr/local/bin/ru_address", line 11, in <module>
    load_entry_point('ru-address==0.1', 'console_scripts', 'ru_address')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/ru_address-0.1-py3.6.egg/ru_address/command.py", line 5, in <module>
    from ru_address.converter import Converter
  File "/usr/local/lib/python3.6/dist-packages/ru_address-0.1-py3.6.egg/ru_address/converter.py", line 5, in <module>
    from ru_address.source.xml import Definition
ModuleNotFoundError: No module named 'ru_address.source'

$ python3 --version
Python 3.6.3

**Comment by Grohotun** [comment]
@shadz3rg та же проблема, Python 2.7.14

**Comment by Grohotun** [comment]
@unwo нужно скопировать папки resources, source в папку с билденным модулем, тогда все заработает.

**Comment by ashkart** [comment]
я вот скопировал, но чет все равно та же ошибка. даже перебилдил. Плюнул на это дело в итоге. Вечно с этим питоном такая пляска с бубном.

**Comment by ghost** [comment]
**Grohotun** а нельзя ли поподробнее. Исполняемый файл появляется в папке /usr/local/bin но запуск с той же ошибкой что и у @unwo

**Comment by Keyzi0** [comment]
> **Grohotun** а нельзя ли поподробнее. Исполняемый файл появляется в папке /usr/local/bin но запуск с той же ошибкой что и у @unwo

если после установки пакета вываливается ошибка  "ModuleNotFoundError: No module named 'ru_address.source'" 
- Идем в директорию откуда устанавливался пакет: **ru_address-master\ru_address**
- Копируем папки: **resources** и **source** в **ru_address-master\build\lib\ru_address**
- Устанавливаем пакет повторно командой: **python полный_путь_к_папке\ru_address-master\setup.py install**
- Проверяем, должно работать

Еще интересный баг, при попытке установки командой **pip install ru_address** ругается что не может найти. При попытке установки командой **git clone https://github.com/shadz3rg/ru_address.git && cd ru_address && python setup.py install** отваливается с ошибкой кодировки в файле **README.rst**, так что пришлось скачать исходник, распаковать его и удалить содержимое **README.rst** после чего пакет устанавливается командой **python полный_путь_к_пакету_\setup.py install**

**Comment by shadz3rg** [comment]
@KeyziTheOne Спасибо за фидбэк. 
Вариант установки через pip убрал, установка вручную теперь работает как надо.
