### ISSUE TITLE
Обваливается при выполнении

### ISSUE THREAD

**Issue by fizmatovec** [shadz3rg/ru_address#2]
![Снимок экрана от 2019-09-25 11-32-55](https://user-images.githubusercontent.com/13299799/65583727-6dab4d00-df88-11e9-9e19-c9f7c0778fdf.png)

Обваливается при запуске с такой ошибкой

**Comment by MrBrain** [comment]
<unknown>:1:12263619215: unclosed token

<img width="1280" alt="Снимок экрана 2019-09-26 в 20 05 31" src="https://user-images.githubusercontent.com/54673695/65709259-1052f100-e099-11e9-88a1-c52e7d9432ad.png">
<img width="1280" alt="Снимок экрана 2019-09-26 в 20 05 31" src="https://user-images.githubusercontent.com/54673695/65709274-1ba61c80-e099-11e9-8d06-f7c79d704dd6.png">

**Comment by MrBrain** [comment]
как исправить ошибку?

**Comment by Jugador1991** [comment]
> ![Снимок экрана от 2019-09-25 11-32-55](https://user-images.githubusercontent.com/13299799/65583727-6dab4d00-df88-11e9-9e19-c9f7c0778fdf.png)
> 
> Обваливается при запуске с такой ошибкой

Название файла. переименуйте .XML на .xml скрипт судя пов сему чувствителен к регистру, у налоговая меняет названия как душе угодно

**Comment by Jugador1991** [comment]
> :1:12263619215: unclosed token
> 
> <img alt="Снимок экрана 2019-09-26 в 20 05 31" width="1280" src="https://user-images.githubusercontent.com/54673695/65709259-1052f100-e099-11e9-88a1-c52e7d9432ad.png">
> 
> <img alt="Снимок экрана 2019-09-26 в 20 05 31" width="1280" src="https://user-images.githubusercontent.com/54673695/65709274-1ba61c80-e099-11e9-8d06-f7c79d704dd6.png">

А вот реально, как с этим справиться хз( та-же ошибка, на 80 +- процентах.(

**Comment by shadz3rg** [comment]
> > :1:12263619215: unclosed token
> 
> А вот реально, как с этим справиться хз( та-же ошибка, на 80 +- процентах.(

Давно не пользуюсь этим проектом, но на первый взгляд дамп (от 28.11.2019) собрался штатно.
![image](https://user-images.githubusercontent.com/2261823/69917629-653c2a80-1481-11ea-942f-2ea911034f15.png)
Если кто-нибудь сможет предоставить повторяемый тест-кейс, то попробую пофиксить.

**Comment by Jugador1991** [comment]
Странно. у меня от 28.11 как раз не собрался.. Но я делал только 1 таблицу addrobj, но не думаю, что дело в этом... на 98% ошибка вылетела.
сам фаил ADDROBJ.xml весил 1,87gb, к сожалению уже удалил его. 
Может быть подскажите, как выловить проблему? Могу перераспаковать заного и попробуем сравнить хэши файлов, может бьется при распаковке? (делал 7z'ом)

**Comment by shadz3rg** [comment]
@Jugador1991 У меня распакованный ADDROBJ весит _2,86 ГБ (3 075 383 628 байт)_. Может макось чудит?)
